apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: ambee-server
    labels:
        app: ambee-server
spec:
    replicas: 3
    template:
        metadata:
            labels:
                app: ambee-server
        spec:
            containers:
                - name: ambee-server
                  image: nidhin_t/ambee-server
                  ports:
                      - containerPort: 8085
