apiVersion: v1
kind: Service
metadata:
    name: ambee-server
spec:
    selector:
        app: ambee-server
    type: LoadBalancer
    ports:
        - name: http
          protocol: TCP
          port: 8085
          targetPort: 8085
